name: Deploy on PR comment

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Deploy
        run: echo "Deploying your app because the manager said the magic word deployyy"

        
