name: MERN Continuous Deployment

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 
  
jobs:
  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend code
        uses: actions/checkout@v4.2.2
        with:
          repository: TilleyCodes/inventory-manager-frontend
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test
  
  backend-tests:
      name: Run Backend Tests
      runs-on: ubuntu-latest

       services:
        mongo:
          image: mongo:6
          ports:
            - 27017:27017
          options: >-
            --health-cmd "mongosh --eval 'db.adminCommand(\"ping"\)'"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      
      env:
        MONGO_URI: mongodb://localhost:27017/testdb

      steps:
      - name: Checkout Backend code
        uses: actions/checkout@v4.2.2
        with:
          repository: TilleyCodes/inventory-manager-backend
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test